language: node_js
cache:
  directories:
  - node_modules
  - "~/.npm"
node_js:
- '12'
git:
  depth: 3
script:
- yarn setup
- yarn test
- yarn lint
notifications:
  email:
    reciepients:
    - ingecarlos.gutierrez@gmail.com
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: VuHOR2xa2xD1NSKvlPBgq9maW3yl/OjqmA64w9GJuf73bLT3dMvqOHiiBT1EI31i34Ld1f+lz40irX4buyYFRFa4hHwsfT0VP94IBxSWtQimHyr+6YAJaQeEc6HW0DkiZlTHmFev19/wje+xaK5feXPmCbP+1NdBVQbc+4YTtdgQcT082+lMu2Lgl4hz8OTjZWdEdDTwvTN7I2ZksR2iBqlFAJ5NOwFQAvqMEMPCtbeJtmm5nrDS6w/7XAyj1P7XcjX20gil7C2O+qfYrHhxHkTR91PxgKOpxcYTzKgutbW4Lsb0rbkFz6xq8BpvJbLKDU4/tZXFDgFktVk2lVdw5rGywD+QoSzVYZujSXdv1FCbGOLPt1uPFECY8u7C0YCzT4q9BoMPP8qIIiUe70k3ytYrgM6ws0c7byg0XsUuzuxltB+Lx65KobXpEzz660+7CzF24BMbcWc5GC3//SuWjPWKU5zODaIHn1s/KrgG5VLpAMPmnmE35Cq9r7V19gXmHS8ECwIjqPQ4jkajHqTEu8iwFGq97dV+GicamTK+UVsqlmcBtffYHzZEeYbm4rQqxnPRCg7909DC3DYzcTEpE9UtYW8f4oDtHdU3JnZEhzp/1W0QPRNMAFrncgUH9wO6BTaWMMoD70oj5moYCNsG+Zo2P6fTP/lwAHAyk5hjYO8=
  app: trelloapplicationmaster
  on:
    repo: SWAT-PMP-Master/Backend
